project='Mäterial'
full_description=[[<p style="text-align: center"><img src="extra/header.png" alt="Mäterial, an immeditate mode ui for Love2d" height="256px"></p>

Mäterial is an immediate mode UI library for [LÖVE](https://love2d.org) that uses the [Material Design](https://material.io) specs.]]
format='discount'
file={'core', 'init.lua'}
topics={'EXTENDING_LIBRARY.md'}
examples={'examples/buttons/buttons.lua', 'examples/inputs/inputs.lua'}
dir='docs'
pretty='lxsh'
style='!fixed'